### PR TITLE
Start using codeql unbundle

### PR DESCRIPTION
**Pull request by rneatherway**

### CODE REVIEW

**Comment by rneatherway** [comment]
This has to wait for https://github.com/github/codeql-action/tree/codeql-bundle-20210824 to be in the toolcache. Will check back in a week.

**Review by robertbrignull — APPROVED** [review]
👍

**Comment by rneatherway** [comment]
I had to use a zip extension, otherwise a sanity check fails.

**Comment by rneatherway** [comment]
Successful run: https://github.com/dsp-testing/qc-controller/actions/runs/1229692694

**Pull request merged**
